import { Inter, Cabin, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import ProfileBar from "./components/ProfileBar";
import Provider from "./Provider";
const inter = Inter({ subsets: ["latin"] });
const cabin = Cabin({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mesh Lock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-row bg-white`}>
        <Provider>
          <Sidebar></Sidebar>
          {children}
          <ProfileBar></ProfileBar>
        </Provider>
      </body>
    </html>
  );
}
